name: Checkmarx One Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: bako-nfr
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://eu.ast.checkmarx.net
          cx_tenant: bako-nfr
          cx_client_id: GitHub_client
          cx_client_secret: SMwtkCPntMIADDNJma0JPOlgnI2RCYab
          additional_params: --tags galactica-team --threshold "sast-high=1"
