# This workflow is to automate Checkmarx SAST scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_URL
#   - CHECKMARX_USER
#   - CHECKMARX_PASSWORD
#   - CHECKMARX_CLIENT_SECRET
#
# The following variables must be inserted below:
#   - <ProjectName>
#
# Update the 'team' field to reflect the team name used in Checkmarx.
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx CxFlow Action
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 #Github Action version
      with:
        base_url: https://eu.ast.checkmarx.net # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.SECRET }} # To be stored in GitHub Secrets.
        project: ${{ secrets.CHECKMARX_PROJECT }} # <-- Insert Checkmarx SAST Project Name
        team: /CxServer/SP/Company
        portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
        sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
        portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
        sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
